[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "arcgis"
description = "ArcGIS Python API"
authors = [
    { name = "Suhendra", email = "suhendra0812@gmail.com" },
]
version = "0.0.1"
dependencies = [
    "requests>=2.31.0"
]